version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task --list

  bootstrap:
    desc: install deps
    aliases: [b]
    deps: [bootstrap-go, bootstrap-js]

  bootstrap-go:
    desc: install go deps
    aliases: [bg]
    cmds:
      - cd go
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest

  bootstrap-js:
    desc: install js deps
    aliases: [bj]
    cmds:
      - cd js && npm install

  connect-gen-js:
    desc: connect generate js proto
    aliases: [cj]
    cmds:
      - |
        cd js && \
        mkdir -p src/gen/eliza && \
        PATH=$PATH:$(pwd)/node_modules/.bin protoc -I ../proto \
          --es_out src/gen/eliza \
          --es_opt target=js \
          --connect-es_out src/gen/eliza \
          --connect-es_opt target=js \
          eliza.proto

  connect-gen-go:
    desc: connect generate js proto
    aliases: [cg]
    cmds:
      - |
        cd go && \
        mkdir -p internal/gen/eliza/ && \
        protoc -I ../proto \
          --go_out internal/gen/eliza --go_opt=paths=source_relative \
          --connect-go_out internal/gen/eliza --connect-go_opt=paths=source_relative \
          eliza.proto

  run-js-dev:
    desc: run web ui in dev mode
    aliases: [rj]
    cmds:
      - |
        cd js && \
        esbuild src/index.ts --serve=localhost:3000 --servedir=www --outdir=www --bundle --global-name=eliza

  run-go-dev:
    desc: run connect server in dev mode
    aliases: [rg]
    cmds:
      - |
        cd go && \
        go run main.go
